# Generated by Django 2.0 on 2020-01-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='created1_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
